### PR TITLE
Systemd 245.4 4ubuntu3.22

### PR DESCRIPTION
**Pull request by 13r0ck**

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
The Jammy binary builds are all failing right now.

**Review by jacobgkau — COMMENTED** [review]
The Jammy binary builds are all failing right now.

<details>
<summary>Output for the build failing locally:</summary>

```
dpkg-buildpackage: info: source package systemd
dpkg-buildpackage: info: source version 245.4-4ubuntu3.22pop0
dpkg-buildpackage: info: source distribution focal
dpkg-buildpackage: info: source changed by Brock Szuszczewicz <brock@system76.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build .
 debian/rules clean
dh clean --without autoreconf --buildsystem=meson
   debian/rules override_dh_auto_clean
make[1]: Entering directory '/home/jacob/Work/systemd'
dh_auto_clean --builddirectory=build-deb
rm -rf debian/install/ debian/shlibs.local
# remove Python byte code files
rm -rf tools/__pycache__/
rm -rf tools/chromiumos/__pycache__/
rm -f po/systemd.pot
make[1]: Leaving directory '/home/jacob/Work/systemd'
   dh_clean -O--buildsystem=meson
 debian/rules binary
dh binary --without autoreconf --buildsystem=meson
   dh_update_autotools_config -O--buildsystem=meson
   debian/rules override_dh_auto_configure
make[1]: Entering directory '/home/jacob/Work/systemd'
dh_auto_configure --builddirectory=build-deb \
	-- -Db_lto=true -Db_pie=true -Drootlibdir=/lib/x86_64-linux-gnu -Dsplit-usr=true -Duser-path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin -Dversion-tag="245.4-4ubuntu3.22pop0" -Dquotaon-path=/sbin/quotaon -Dquotacheck-path=/sbin/quotacheck -Dkmod-path=/bin/kmod -Dkexec-path=/sbin/kexec -Dsulogin-path=/sbin/sulogin -Dmount-path=/bin/mount -Dumount-path=/bin/umount -Dloadkeys-path=/bin/loadkeys -Dsetfont-path=/bin/setfont -Dnologin-path=/usr/sbin/nologin -Dtelinit-path=/lib/sysvinit/telinit -Dsysvinit-path=/etc/init.d -Dsysvrcnd-path=/etc -Ddebug-shell=/bin/bash -Dzshcompletiondir=/usr/share/zsh/vendor-completions -Ddbuspolicydir=/usr/share/dbus-1/system.d/ -Dsupport-url=http://www.ubuntu.com/support -Ddefault-kill-user-processes=false -Ddefault-hierarchy=hybrid -Dpamconfdir=no -Drpmmacrosdir=no -Dqrencode=false -Dvconsole=false -Dfirstboot=false -Dxkbcommon=false -Dwheel-group=false -Drepart=false -Duserdb=false -Dhomed=false -Dfdisk=false -Dpwquality=false -Dp11kit=false -Dntp-servers="ntp.ubuntu.com" -Ddns-servers='' -Dlink-udev-shared=false -Dsystem-uid-max=999 -Dsystem-gid-max=999 -Dnobody-user=nobody -Dnobody-group=nogroup -Dbump-proc-sys-fs-nr-open=false -Ddev-kvm-mode=0660 -Dgroup-render-mode=0660 -Ddefault-net-naming-scheme=v245  -Ddefault-dnssec=no -Dtpm-pcrindex=12 -Dselinux=true -Dhwdb=true -Dsysusers=true -Dinstall-tests=true -Defi=true -Dman=true -Dnss-myhostname=true -Dnss-mymachines=true -Dnss-resolve=true -Dnss-systemd=true -Dresolve=true -Dlink-systemctl-shared=false -Daudit=true -Dlibcryptsetup=true -Dcoredump=true -Delfutils=true -Dapparmor=true -Dlibidn2=true -Dlibiptc=true -Dlibcurl=true -Dimportd=true -Dmicrohttpd=true -Dgnutls=true -Dpcre2=true 
	cd build-deb && LC_ALL=C.UTF-8 meson .. --wrap-mode=nodownload --buildtype=plain --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libdir=lib/x86_64-linux-gnu --libexecdir=lib/x86_64-linux-gnu -Db_lto=true -Db_pie=true -Drootlibdir=/lib/x86_64-linux-gnu -Dsplit-usr=true -Duser-path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin -Dversion-tag=245.4-4ubuntu3.22pop0 -Dquotaon-path=/sbin/quotaon -Dquotacheck-path=/sbin/quotacheck -Dkmod-path=/bin/kmod -Dkexec-path=/sbin/kexec -Dsulogin-path=/sbin/sulogin -Dmount-path=/bin/mount -Dumount-path=/bin/umount -Dloadkeys-path=/bin/loadkeys -Dsetfont-path=/bin/setfont -Dnologin-path=/usr/sbin/nologin -Dtelinit-path=/lib/sysvinit/telinit -Dsysvinit-path=/etc/init.d -Dsysvrcnd-path=/etc -Ddebug-shell=/bin/bash -Dzshcompletiondir=/usr/share/zsh/vendor-completions -Ddbuspolicydir=/usr/share/dbus-1/system.d/ -Dsupport-url=http://www.ubuntu.com/support -Ddefault-kill-user-processes=false -Ddefault-hierarchy=hybrid -Dpamconfdir=no -Drpmmacrosdir=no -Dqrencode=false -Dvconsole=false -Dfirstboot=false -Dxkbcommon=false -Dwheel-group=false -Drepart=false -Duserdb=false -Dhomed=false -Dfdisk=false -Dpwquality=false -Dp11kit=false -Dntp-servers=ntp.ubuntu.com -Ddns-servers= -Dlink-udev-shared=false -Dsystem-uid-max=999 -Dsystem-gid-max=999 -Dnobody-user=nobody -Dnobody-group=nogroup -Dbump-proc-sys-fs-nr-open=false -Ddev-kvm-mode=0660 -Dgroup-render-mode=0660 -Ddefault-net-naming-scheme=v245 -Ddefault-dnssec=no -Dtpm-pcrindex=12 -Dselinux=true -Dhwdb=true -Dsysusers=true -Dinstall-tests=true -Defi=true -Dman=true -Dnss-myhostname=true -Dnss-mymachines=true -Dnss-resolve=true -Dnss-systemd=true -Dresolve=true -Dlink-systemctl-shared=false -Daudit=true -Dlibcryptsetup=true -Dcoredump=true -Delfutils=true -Dapparmor=true -Dlibidn2=true -Dlibiptc=true -Dlibcurl=true -Dimportd=true -Dmicrohttpd=true -Dgnutls=true -Dpcre2=true
The Meson build system
Version: 0.61.2
Source dir: /home/jacob/Work/systemd
Build dir: /home/jacob/Work/systemd/build-deb
Build type: native build

../meson.build:3:0: ERROR: Value "v245" (of type "string") for combo option "default net.naming-scheme= value" is not one of the choices. Possible choices are (as string): "latest", "v238", "v239", "v240".

A full log can be found at /home/jacob/Work/systemd/build-deb/meson-logs/meson-log.txt
	cd build-deb && tail -v -n \+0 meson-logs/meson-log.txt
==> meson-logs/meson-log.txt <==
Build started at 2023-06-02T11:26:10.835038
Main binary: /usr/bin/python3
Build Options: -Db_lto=true -Db_pie=true -Drootlibdir=/lib/x86_64-linux-gnu -Dsplit-usr=true -Duser-path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin -Dversion-tag=245.4-4ubuntu3.22pop0 -Dquotaon-path=/sbin/quotaon -Dquotacheck-path=/sbin/quotacheck -Dkmod-path=/bin/kmod -Dkexec-path=/sbin/kexec -Dsulogin-path=/sbin/sulogin -Dmount-path=/bin/mount -Dumount-path=/bin/umount -Dloadkeys-path=/bin/loadkeys -Dsetfont-path=/bin/setfont -Dnologin-path=/usr/sbin/nologin -Dtelinit-path=/lib/sysvinit/telinit -Dsysvinit-path=/etc/init.d -Dsysvrcnd-path=/etc -Ddebug-shell=/bin/bash -Dzshcompletiondir=/usr/share/zsh/vendor-completions -Ddbuspolicydir=/usr/share/dbus-1/system.d/ -Dsupport-url=http://www.ubuntu.com/support -Ddefault-kill-user-processes=false -Ddefault-hierarchy=hybrid -Dpamconfdir=no -Drpmmacrosdir=no -Dqrencode=false -Dvconsole=false -Dfirstboot=false -Dxkbcommon=false -Dwheel-group=false -Drepart=false -Duserdb=false -Dhomed=false -Dfdisk=false -Dpwquality=false -Dp11kit=false -Dntp-servers=ntp.ubuntu.com -Ddns-servers= -Dlink-udev-shared=false -Dsystem-uid-max=999 -Dsystem-gid-max=999 -Dnobody-user=nobody -Dnobody-group=nogroup -Dbump-proc-sys-fs-nr-open=false -Ddev-kvm-mode=0660 -Dgroup-render-mode=0660 -Ddefault-net-naming-scheme=v245 -Ddefault-dnssec=no -Dtpm-pcrindex=12 -Dselinux=true -Dhwdb=true -Dsysusers=true -Dinstall-tests=true -Defi=true -Dman=true -Dnss-myhostname=true -Dnss-mymachines=true -Dnss-resolve=true -Dnss-systemd=true -Dresolve=true -Dlink-systemctl-shared=false -Daudit=true -Dlibcryptsetup=true -Dcoredump=true -Delfutils=true -Dapparmor=true -Dlibidn2=true -Dlibiptc=true -Dlibcurl=true -Dimportd=true -Dmicrohttpd=true -Dgnutls=true -Dpcre2=true -Dprefix=/usr -Dlibdir=lib/x86_64-linux-gnu -Dlibexecdir=lib/x86_64-linux-gnu -Dlocalstatedir=/var -Dsysconfdir=/etc -Dbuildtype=plain -Dwrap_mode=nodownload
Python system: Linux
The Meson build system
Version: 0.61.2
Source dir: /home/jacob/Work/systemd
Build dir: /home/jacob/Work/systemd/build-deb
Build type: native build

../meson.build:3:0: ERROR: Value "v245" (of type "string") for combo option "default net.naming-scheme= value" is not one of the choices. Possible choices are (as string): "latest", "v238", "v239", "v240".
dh_auto_configure: error: cd build-deb && LC_ALL=C.UTF-8 meson .. --wrap-mode=nodownload --buildtype=plain --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libdir=lib/x86_64-linux-gnu --libexecdir=lib/x86_64-linux-gnu -Db_lto=true -Db_pie=true -Drootlibdir=/lib/x86_64-linux-gnu -Dsplit-usr=true -Duser-path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin -Dversion-tag=245.4-4ubuntu3.22pop0 -Dquotaon-path=/sbin/quotaon -Dquotacheck-path=/sbin/quotacheck -Dkmod-path=/bin/kmod -Dkexec-path=/sbin/kexec -Dsulogin-path=/sbin/sulogin -Dmount-path=/bin/mount -Dumount-path=/bin/umount -Dloadkeys-path=/bin/loadkeys -Dsetfont-path=/bin/setfont -Dnologin-path=/usr/sbin/nologin -Dtelinit-path=/lib/sysvinit/telinit -Dsysvinit-path=/etc/init.d -Dsysvrcnd-path=/etc -Ddebug-shell=/bin/bash -Dzshcompletiondir=/usr/share/zsh/vendor-completions -Ddbuspolicydir=/usr/share/dbus-1/system.d/ -Dsupport-url=http://www.ubuntu.com/support -Ddefault-kill-user-processes=false -Ddefault-hierarchy=hybrid -Dpamconfdir=no -Drpmmacrosdir=no -Dqrencode=false -Dvconsole=false -Dfirstboot=false -Dxkbcommon=false -Dwheel-group=false -Drepart=false -Duserdb=false -Dhomed=false -Dfdisk=false -Dpwquality=false -Dp11kit=false -Dntp-servers=ntp.ubuntu.com -Ddns-servers= -Dlink-udev-shared=false -Dsystem-uid-max=999 -Dsystem-gid-max=999 -Dnobody-user=nobody -Dnobody-group=nogroup -Dbump-proc-sys-fs-nr-open=false -Ddev-kvm-mode=0660 -Dgroup-render-mode=0660 -Ddefault-net-naming-scheme=v245 -Ddefault-dnssec=no -Dtpm-pcrindex=12 -Dselinux=true -Dhwdb=true -Dsysusers=true -Dinstall-tests=true -Defi=true -Dman=true -Dnss-myhostname=true -Dnss-mymachines=true -Dnss-resolve=true -Dnss-systemd=true -Dresolve=true -Dlink-systemctl-shared=false -Daudit=true -Dlibcryptsetup=true -Dcoredump=true -Delfutils=true -Dapparmor=true -Dlibidn2=true -Dlibiptc=true -Dlibcurl=true -Dimportd=true -Dmicrohttpd=true -Dgnutls=true -Dpcre2=true returned exit code 1
make[1]: *** [debian/rules:185: override_dh_auto_configure] Error 255
make[1]: Leaving directory '/home/jacob/Work/systemd'
make: *** [debian/rules:322: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
```
</details>

**Comment by 13r0ck** [comment]
@jacobgkau this is merging into focal, jammy builds don't matter

**Review by jacobgkau — APPROVED** [review]
Regression testing passed on Focal:
- [X] Confirm all Pop!_OS patches are still present
- [X] Shutdown/reboot work
- [X] Able to use the boot menu & updating initramfs works normally (systemd-boot)
- [X] Service management works normally
- [X] Virtual machine works
- [X] Suspend/resume works (in NVIDIA mode and Integrated mode)
- [X] DNS resolution works w/ automatic and custom settings (systemd-resolved)
- [X] Disabling/enabling systemd-timesyncd NTP works (timedatectl)
- [X] Able to view logs with journalctl (systemd-journald)
- [X] Check for Steam packaging issues
  - [X] Make sure Steam can be installed with new systemd
  - [X] Make sure systemd can be updated with Steam installed

**Pull request merged**
