### PR TITLE
Depend on Chrony in systemd rather than pop-os/desktop

### PR DESCRIPTION
**Pull request by 13r0ck**
requires https://github.com/pop-os/desktop/pull/114

### CODE REVIEW

**Comment by jacobgkau** [comment]
> requires [pop-os/desktop#114](https://github.com/pop-os/desktop/pull/114)

Again, for the record, this does not require pop-os/desktop#114, pop-os/desktop#114 just requires this.

**Comment by 13r0ck** [comment]
Sure, "requires" may be the wrong word, just linking the two for current and future reference

**Comment by jacobgkau** [comment]
"required by" is probably what you were looking for.

**Review by jackpot51 — DISMISSED** [review]

**Review by jacobgkau — COMMENTED** [review]
When attempting to install `openntpd`, `chrony` is correctly removed. However, when attempting to remove `chrony`, more than just `openntpd` is installed, and a number of seemingly unrelated packages (including `system76-driver`) are also removed:

Screenshot from 2023-04-07 15-45-42

This shouldn't happen unless someone runs it manually, but it's a little concerning to see and I'd like to understand why it's happening. If I proceed with the above operation, installing `chrony` again doesn't pull the rest of those packages back in again, but I'm able to install them again manually (with or without `chrony`). Any idea what's going on with this?

If we need to, we could drop the `openntpd` option and just depend exclusively on `chrony` like `pop-desktop` already was. Bringing up the possibility of other options was just an attempt to not box people in unnecessarily as we export this dependency to our supported Ubuntu installs.

**Comment by jacobgkau** [comment]
I think the above behavior might actually be an apt bug, rather than a packaging issue. I found a `FIXME` line in a very relevant portion of apt's code: https://salsa.debian.org/apt-team/apt/-/blob/main/apt-pkg/algorithms.cc#L1059 

Still looking into this to try to confirm and/or fix the bug.

**Comment by 13r0ck** [comment]
I just dropped openntpd

**Review by jacobgkau — APPROVED** [review]
Attempting to remove `chrony` before this change:

Screenshot from 2023-04-12 12-40-18

Interestingly, even with https://github.com/pop-os/desktop/pull/114 also installed, attempting to remove `chrony` after this change still refers to `pop-desktop` directly and only indirectly mentions a `systemd` component:

Screenshot from 2023-04-12 12-41-35

`aptitude why` does function as expected (reporting that `systemd` depends on `chrony`), although that program isn't installed by default. But at least this side of the change is needed to support Ubuntu, and there is no functional impact here, so approving.

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
I've found a solution for the apt bug I described and opened an upstream merge request for it: https://salsa.debian.org/apt-team/apt/-/merge_requests/292 

If that makes it in, then we may be able to add NTP client alternatives back once we have it. (Even if we don't, this was incorrect behavior and would probably also affect other "or group" dependencies.)

**Pull request merged**
