### PR TITLE
chore: Import Ubuntu patches

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Review by jacobgkau — CHANGES_REQUESTED** [review]
Got an error message installing Steam:

```
system76@pop-os:~$ apt policy systemd steam
systemd:
  Installed: 245.4-4ubuntu3.15pop0~1642200283~20.04~1436635
  Candidate: 245.4-4ubuntu3.15pop0~1642200283~20.04~1436635
  Version table:
 *** 245.4-4ubuntu3.15pop0~1642200283~20.04~1436635 1002
       1002 http://apt.pop-os.org/staging/systemd focal/main amd64 Packages
        100 /var/lib/dpkg/status
     245.4-4ubuntu3.15 500
        500 http://us.archive.ubuntu.com/ubuntu focal-security/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
     245.4-4ubuntu3.13pop0~1631829301~20.04~a958ca9 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
     245.4-4ubuntu3 500
        500 http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages
steam:i386:
  Installed: (none)
  Candidate: 1:1.0.0.71-1pop1~1631241010~20.04~4ff6817
  Version table:
     1:1.0.0.71-1pop1~1631241010~20.04~4ff6817 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
     1:1.0.0.61-2ubuntu3 500
        500 http://us.archive.ubuntu.com/ubuntu focal/multiverse i386 Packages
system76@pop-os:~$ sudo apt install steam
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 steam:i386 : Depends: libudev1:i386 but it is not going to be installed
              Recommends: libasound2-plugins:i386 but it is not going to be installed
              Recommends: libsdl2-2.0-0:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
system76@pop-os:~$
```

**Comment by jacobgkau** [comment]
The corresponding version of `libudev1:i386` is not available:

```
system76@pop-os:~$ apt policy libudev1:i386
libudev1:i386:
  Installed: (none)
  Candidate: 245.4-4ubuntu3.13pop0~1631829301~20.04~a958ca9
  Version table:
     245.4-4ubuntu3.15 500
        500 http://us.archive.ubuntu.com/ubuntu focal-security/main i386 Packages
        500 http://us.archive.ubuntu.com/ubuntu focal-updates/main i386 Packages
     245.4-4ubuntu3.13pop0~1631829301~20.04~a958ca9 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
     245.4-4ubuntu3 500
        500 http://us.archive.ubuntu.com/ubuntu focal/main i386 Packages
```

Confirmed this was not an issue on the Impish version of this branch; it had a version available from the staging repo.

**Comment by mmstick** [comment]
Good thing we're hosting our packages for impish. Maybe Launchpad is not be building because the version string isn't the same as Ubuntu's?

**Comment by jacobgkau** [comment]
Still not seeing the staging repo provide `libudev1:i386`. [steam3.txt](https://github.com/pop-os/systemd/files/7900778/steam3.txt)

The version of systemd being reported by apt is still below Ubuntu's own version, in case it's relevant:
```
system76@pop-os:~$ apt policy systemd
systemd:
  Installed: 245.4-4ubuntu3.15~1642621326~20.04~ddd2837
  Candidate: 245.4-4ubuntu3.15~1642621326~20.04~ddd2837
  Version table:
     245.4-4ubuntu3.15 500
        500 http://us.archive.ubuntu.com/ubuntu focal-security/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
 *** 245.4-4ubuntu3.15~1642621326~20.04~ddd2837 1002
       1002 http://apt.pop-os.org/staging/systemd focal/main amd64 Packages
        100 /var/lib/dpkg/status
     245.4-4ubuntu3.13pop0~1631829301~20.04~a958ca9 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
     245.4-4ubuntu3 500
        500 http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages
```

**Comment by jacobgkau** [comment]
This is still not built on i386.

**Comment by jackpot51** [comment]
> This is still not built on i386.

I will look into it.

**Comment by jackpot51** [comment]
I rewrote it to explicitly list all archs I want to build it for

**Review by jacobgkau — APPROVED** [review]
- [X] Confirm all Pop!_OS patches are still present
- [X] Shutdown/reboot work
- [X] Able to use the boot menu & updating initramfs works normally (systemd-boot)
- [X] Service management works normally
- [X] Virtual machine works
- [X] Suspend/resume works
    - [X] Integrated
    - [X] NVIDIA
- [X] DNS resolution works w/ automatic and custom settings (systemd-resolved)
- [X] NTP works (systemd-timesyncd)
- [X] Able to view logs with journalctl (systemd-journald)
- [X] Check for Steam packaging issues
    - [X] Make sure Steam can be installed with new systemd
    - [X] Make sure systemd can be updated with Steam installed

**Pull request merged**
